### ISSUE TITLE
question: how come it's so fast?

### ISSUE THREAD

**Issue by alessioalex** [mcollina/fastparallel#2]
Hey there, I didn't really look that closely at the code to compare it with other libraries out there. Can you perhaps add a tiny info into the `README` as to the reason to its fastness? :+1:

**Comment by mcollina** [comment]
A simple explanation is https://github.com/mcollina/fastparallel#caveats.
This library is caching funcitons a lot.

The second point are V8 optimizations: thanks, to caching, the functions can be optimized by V8 (if they are optimizable, and I took great care of making them so).

The third point is don't use arrays. A linked list implemented via processes is much faster if you don't need to access elements in between.

The 4th point, which is usually not seen, is that it accept passing a `this`. Thanks to this hack, you can extract your functions, and place them in a outer level where they are not created at every execution.

Is that clear enough? Or is there something that doesn't feel right?

Feel free to send a PR ;).

**Comment by alessioalex** [comment]
Thank you very much for taking the time to write this down, it's pretty clear now!
Btw, I feel this is valuable info which you can add to the `readme`. Literally, copy paste. I'm sure others will be curious as well.
